### ISSUE TITLE
mxnet build error:  with flag USE_TENSORRT

### ISSUE THREAD

**Issue by sleepwalker2017** [apache/incubator-mxnet#14369]
I'm working on ubuntu 16.04 and building mxnet from the latest source.

make -j USE_CPP_PACKAGE=1 USE_TENSORRT

here is the error list:

src/executor/onnx_to_tensorrt.cc: In function ‘nvinfer1::ICudaEngine* onnx_to_tensorrt::onnxToTrtCtx(const string&, int32_t, size_t, nvinfer1::ILogger::Severity, bool)’:
src/executor/onnx_to_tensorrt.cc:99:19: error: expected id-expression before ‘::’ token
   ::ONNX_NAMESPACE::ModelProto parsed_model;
                   ^
src/executor/onnx_to_tensorrt.cc:102:8: error: ‘parsed_model’ was not declared in this scope
   if (!parsed_model.ParseFromString(onnx_model)) {
        ^
src/executor/onnx_to_tensorrt.cc:111:27: error: expected id-expression before ‘::’ token
           ::ONNX_NAMESPACE::NodeProto const& node =
                           ^
src/executor/onnx_to_tensorrt.cc:114:27: error: ‘node’ was not declared in this scope
                << " [" << node.op_type();

**Comment by piyushghai** [comment]
@sleepwalker2017 Can you tell me a bit more information about your system ?

You can use this template : 

## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by piyushghai** [comment]
@mxnet-label-bot Add [Build]

**Comment by sleepwalker2017** [comment]
solved!
the macro NCNN_NAMESPACE is not defined!

**Comment by chichivica** [comment]
Same issue here.
@sleepwalker2017 Hey! How did you solve that?
