### ISSUE TITLE
Install v0.10.0 errors

### ISSUE THREAD

**Issue by frankpunx** [apache/incubator-mxnet#10174]
## Description
1. Can't do submodule update after checkout v0.10.0
2. Can't compile

## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.14')
('Compiler     :', 'GCC 7.2.1 20171224')
('Build        :', ('default', 'Jan  5 2018 10:41:29'))
('Arch         :', ('64bit', ''))
------------Pip Info-----------
('Version      :', '9.0.2')
('Directory    :', '/home/ghost/projects/Virtual_envs/FGFA/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Linux-4.15.10-1-ARCH-x86_64-with-glibc2.2.5')
('system       :', 'Linux')
('node         :', 'ghost')
('release      :', '4.15.10-1-ARCH')
('version      :', '#1 SMP PREEMPT Thu Mar 15 12:24:34 UTC 2018')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', '')
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               60
Model name:          Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
Stepping:            3
CPU MHz:             1695.967
CPU max MHz:         3500.0000
CPU min MHz:         800.0000
BogoMIPS:            4988.10
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt ibpb ibrs stibp dtherm ida arat pln pts
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0386 sec, LOAD: 1.3605 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.2636 sec, LOAD: 0.1239 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1325 sec, LOAD: 0.9094 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0930 sec, LOAD: 0.7247 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.3037 sec, LOAD: 0.3090 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1009 sec, LOAD: 0.8995 sec.


```

## Error Message:

(Compiling error)
```bash
src/operator/custom/./native_op-inl.h:204:36: error: no matching function for call to ‘std::vector<unsigned int*>::push_back(nnvm::dim_t*)’
shapes.push_back(iter->data());
^
In file included from /usr/include/c++/7.3.0/vector:64:0,
from /home/ghost/projects/incubator-mxnet/dmlc-core/include/dmlc/logging.h:13,
from src/operator/custom/./native_op-inl.h:10,
from src/operator/custom/native_op.cc:7:
/usr/include/c++/7.3.0/bits/stl_vector.h:939:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
push_back(const value_type& __x)
^~~~~~~~~
/usr/include/c++/7.3.0/bits/stl_vector.h:939:7: note: no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int* const&’
/usr/include/c++/7.3.0/bits/stl_vector.h:953:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
push_back(value_type&& _x)
^~~~~~~~~
/usr/include/c++/7.3.0/bits/stl_vector.h:953:7: note: no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
src/operator/contrib/proposal.cc: In instantiation of ‘void mxnet::op::ProposalOp::Forward(const mxnet::OpContext&, const std::vectormxnet::TBlob&, const std::vectormxnet::OpReqType&, const std::vectormxnet::TBlob&, const std::vectormxnet::TBlob&) [with xpu = mshadow::cpu]’:
src/operator/contrib/proposal.cc:458:1: required from here
src/operator/contrib/proposal.cc:329:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (index_t i = 0; i < num_anchors; ++i) {
^
src/operator/contrib/proposal.cc:330:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (index_t j = 0; j < height; ++j) {
^
src/operator/contrib/proposal.cc:331:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (index_t k = 0; k < width; ++k) {
^
In file included from src/operator/custom/native_op.cc:7:0:
src/operator/custom/./native_op-inl.h: In instantiation of ‘void mxnet::op::NativeOp::SyncVec(const std::vectormxnet::TBlob&, const string&, mshadow::Stream, int) [with xpu = mshadow::cpu; std::__cxx11::string = std::__cxx11::basic_string]’:
src/operator/custom/native_op.cc:27:1: required from here
src/operator/custom/./native_op-inl.h:146:24: error: invalid const_cast from type ‘const dim_t {aka const long int*}’ to type ‘mxnet::index_t* {aka unsigned int*}’
shapes.push_back(const_cast<index_t*>(vec[i].shape.data()));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:207: build/src/operator/custom/native_op.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/operator/custom/ndarray_op.cc:7:0:
src/operator/custom/./ndarray_op-inl.h: In member function ‘virtual bool mxnet::op::NDArrayOpProp::InferShape(std::vectornnvm::TShape, std::vectornnvm::TShape, std::vectornnvm::TShape) const’:
src/operator/custom/./ndarray_op-inl.h:116:36: error: no matching function for call to ‘std::vector<unsigned int>::push_back(nnvm::dim_t*)’
shapes.push_back(iter->data());
^
In file included from /usr/include/c++/7.3.0/vector:64:0,
from /home/ghost/projects/incubator-mxnet/dmlc-core/include/dmlc/logging.h:13,
from src/operator/custom/./ndarray_op-inl.h:10,
from src/operator/custom/ndarray_op.cc:7:
/usr/include/c++/7.3.0/bits/stl_vector.h:939:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
push_back(const value_type& __x)
^~~~~~~~~
/usr/include/c++/7.3.0/bits/stl_vector.h:939:7: note: no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int* const&’
/usr/include/c++/7.3.0/bits/stl_vector.h:953:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = unsigned int*; _Alloc = std::allocator<unsigned int*>; std::vector<_Tp, _Alloc>::value_type = unsigned int*]
push_back(value_type&& __x)
^~~~~~~~~
/usr/include/c++/7.3.0/bits/stl_vector.h:953:7: note: no known conversion for argument 1 from ‘nnvm::dim_t* {aka long int*}’ to ‘unsigned int*&&’
make: *** [Makefile:207: build/src/operator/custom/ndarray_op.o] Error 1
```

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. `git clone --recursive https://github.com/apache/incubator-mxnet.git`
2. `cd incubator-mxnet`
3. `git checkout v0.10.0`
4. `git submodule update`
```
(error): Cloning into '/home/ghost/projects/incubator-mxnet/cub'...
error: Server does not allow request for unadvertised object 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Fetched in submodule path 'cub', but it did not contain 89de7ab20167909bc2c4f8acd397671c47cf3c0d. Direct fetching of that commit failed.
```
5. `cd ${MXNET_ROOT}`
6. `make -j4`

## What have you tried to solve it?

1.
2.

**Comment by marcoabreu** [comment]
Hello @frankpunx, v0.10.0 is quite old and it could be possible that the cub-project did a hard push on their repository, invalidating all commit hashes and thus making this dependency unresolvable. 

I would recommend you to upgrade to the latest MXNet version, currently 1.1.0. Would you mind elaborating why you would like to use v0.10.0?

**Comment by frankpunx** [comment]
Hi @marcoabreu , the reason i'm trying to use this version is that I'm trying to clone the [FGFA](https://github.com/msracver/Flow-Guided-Feature-Aggregation) repository and they use this version.

**Comment by marcoabreu** [comment]
I see, thanks! Would you mind trying out whether it works with 1.1.0?

**Comment by frankpunx** [comment]
Hi @marcoabreu , I have tried to install the latest version of MXNet and then I did MAKE -j4 and got this error. Do you have any idea why?

error:
Generator<mshadow::gpu, DType>*)’:
include/mxnet/./../../src/common/random_generator.h:154:5: error: there are no arguments to ‘CUDA_CALL’ that depend on a template parameter, so a declaration of ‘CUDA_CALL’ must be available [-fpermissive]
     CUDA_CALL(cudaMalloc(&inst->states_,
     ^~~~~~~~~
include/mxnet/./../../src/common/random_generator.h:154:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
include/mxnet/./../../src/common/random_generator.h: In static member function ‘static void mxnet::common::random::RandGenerator<mshadow::gpu, DType>::FreeState(mxnet::common::random::RandGenerator<mshadow::gpu, DType>*)’:
include/mxnet/./../../src/common/random_generator.h:159:5: error: there are no arguments to ‘CUDA_CALL’ that depend on a template parameter, so a declaration of ‘CUDA_CALL’ must be available [-fpermissive]
     CUDA_CALL(cudaFree(inst->states_));
     ^~~~~~~~~
In file included from src/operator/nn/cudnn/./../../linalg.h:31:0,
                 from src/operator/nn/cudnn/./../convolution-inl.h:43,
                 from src/operator/nn/cudnn/./cudnn_algoreg-inl.h:34,
                 from src/operator/nn/cudnn/cudnn_algoreg.cc:26:
src/operator/nn/cudnn/./../.././c_lapack_api.h: At global scope:
src/operator/nn/cudnn/./../.././c_lapack_api.h:330:25: note: #pragma message: Warning: lapack usage not enabled, linalg-operators will not be available. Ensure that lapack library is installed and build with USE_LAPACK=1 to get lapack functionalities.
      " functionalities.")
                         ^
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/ghost/projects/incubator-mxnet/mshadow/ -I/home/ghost/projects/incubator-mxnet/dmlc-core/include -fPIC -I/home/ghost/projects/incubator-mxnet/nnvm/include -I/home/ghost/projects/incubator-mxnet/dlpack/include -I/home/ghost/projects/incubator-mxnet/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/ghost/projects/incubator-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/contrib/multibox_target.cc -o build/src/operator/contrib/multibox_target.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/ghost/projects/incubator-mxnet/mshadow/ -I/home/ghost/projects/incubator-mxnet/dmlc-core/include -fPIC -I/home/ghost/projects/incubator-mxnet/nnvm/include -I/home/ghost/projects/incubator-mxnet/dlpack/include -I/home/ghost/projects/incubator-mxnet/nnvm/tvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_USE_CUDNN=1  -I/home/ghost/projects/incubator-mxnet/3rdparty/cub -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/contrib/count_sketch.cc -o build/src/operator/contrib/count_sketch.o
make: *** [Makefile:394: build/src/operator/nn/cudnn/cudnn_algoreg.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by marcoabreu** [comment]
Sorry, I'm not familiar with that part. Maybe @szha @eric-haibin-lin or @cjolivier01 can shed some light here?

**Comment by cjolivier01** [comment]
did you do a git fetch —all  before the submodule update?

**Comment by frankpunx** [comment]
I'm building 1.1 branch.
I have done the following steps:
git clone --recursive https://github.com/apache/incubator-mxnet.git
cd incubator-mxnet
git submodule update
make -4j

**Comment by szha** [comment]
For the submodule problem, it looks like this is due to forced update in dmlc/cub (cc @piiswrong). The rest of the errors look like submodules not being properly updated. Try `git submodule update --init --recursive` and then build again.

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy could you please label the issue Pending requester info

**Comment by kalyc** [comment]
@frankpunx has your issue been resolved? Could you update?

**Comment by piyushghai** [comment]
@frankpunx I tried the same steps but I also did a ```git submodule update --init --recursive``` and it did not give me any errors. 
Please let us know if your issue has been resolved as well with this fix. 
Thanks!

**Comment by yzhliu** [comment]
Please feel free to reopen this issue if you found this issue has not been solved.

**Comment by achalddave** [comment]
For what it's worth, I was able to fix this by following the instructions here: https://gist.github.com/myusuf3/7f645819ded92bda6677 (replicated below):

- Delete the relevant section from the .gitmodules file.
- Stage the .gitmodules changes git add .gitmodules
- Delete the relevant section from .git/config.
- Run git rm --cached path_to_submodule (no trailing slash).
- Run rm -rf .git/modules/path_to_submodule (no trailing slash).
- Commit git commit -m "Removed submodule <name>"
- Delete the now untracked submodule files rm -rf path_to_submodule

to remove the cub submodule, and adding the submodule back with `git submodule add https://github.com/NVlabs/cub.git cub`.

**Comment by ZhuofeiKang** [comment]
Have you solved this error?
