### ISSUE TITLE
Compilation fails with cuDNN and cuda 7.5.18

### ISSUE THREAD

**Issue by vchuravy** [apache/incubator-mxnet#3145]
If I compile the current master with cuDNN enable I encounter many of these errors:

```
src/operator/./cudnn_rnn-inl.h(127): error: argument of type "mshadow::half::half_t *" is incompatible with parameter of type "cudnnTensorDescriptor_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=mshadow::half::half_t]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=mshadow::half::half_t]" 
src/operator/rnn.cu(20): here
```
## Versions:
- `gcc`: 4.9.2
- `cuDNN`: 5.0.4 (according to header file)
- `cuda`: 7.5.18
- `mxnet`: b12f957ac1

**Comment by mli** [comment]
try `git submodule update` or use cudnn 5.1

**Comment by shuokay** [comment]
This maybe caused by https://github.com/dmlc/mxnet/pull/2795, you should update cuda and cudnn to the latest version.

**Comment by vchuravy** [comment]
I have just encountered this again. Features that require specific cuda/cuDNN versions should check for them and either disable themselves or print a error message that prompts the user to update.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
