### ISSUE TITLE
compile mxnet failed?

### ISSUE THREAD

**Issue by WhiteIsClosing** [apache/incubator-mxnet#2662]
I just reinstall ubuntu 16.04 on my work station.
The station has 3 GPUs(NVIDIA GTX 1080).

This is my config.mk file.

```
export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS =

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /usr/local/cuda-8.0/

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =


#----------------------------
# plugins
#----------------------------

# whether to use torch integration. This requires installing torch.
# You also need to add TORCH_PATH/install/lib to your LD_LIBRARY_PATH
# TORCH_PATH = $(HOME)/torch
# MXNET_PLUGINS += plugin/torch/torch.mk

# WARPCTC_PATH = $(HOME)/warp-ctc
# MXNET_PLUGINS += plugin/warpctc/warpctc.mk

# whether to use sframe integration. This requires build sframe
# git@github.com:dato-code/SFrame.git
# SFRAME_PATH = $(HOME)/SFrame
# MXNET_PLUGINS += plugin/sframe/plugin.mk
```

And the compile error information

```
/usr/local/cuda-8.0//bin/nvcc -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/opt/mxnet/mshadow/ -I/opt/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda-8.0//include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=1" -M -MT build/src/ndarray/ndarray_function_gpu.o src/ndarray/ndarray_function.cu >build/src/ndarray/ndarray_function_gpu.d
/usr/local/cuda-8.0//bin/nvcc -c -o build/src/ndarray/ndarray_function_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/opt/mxnet/mshadow/ -I/opt/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda-8.0//include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=1" src/ndarray/ndarray_function.cu
/usr/include/c++/5/ext/new_allocator.h(99): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7537


1 catastrophic error detected in the compilation of "/tmp/tmpxft_00000b91_00000000-7_ndarray_function.cpp1.ii".
Compilation aborted.
Aborted (core dumped)
Makefile:156: recipe for target 'build/src/ndarray/ndarray_function_gpu.o' failed
make: *** [build/src/ndarray/ndarray_function_gpu.o] Error 134
```

A week ago I successfully compile MXnet using the same config.mk , same CUDA ,same CUDNN, same driver and same OS.

Today I reinstall them all and I failed build MXnet.

In the mean time, I can use Theano on my machine.

When I set `USE_CUDA=0`,I can compile MXnet successfully.

How can I solve it?

**Comment by geraint0923** [comment]
I don't know much about mxnet, but it seems that you are using gcc 5.0+ which is not really compatible with cuda since I failed to compile tensorflow with cuda+gcc5. Maybe you can try downgrade gcc.

**Comment by thirdwing** [comment]
The same issue with #2672 

I agree with @geraint0923 . Downgrading should help.

**Comment by junzis** [comment]
Same here. 

Solved by install gcc-4.9 and g++-4.9 from apt. Then update the target gcc and g++ to gcc-4.9 and g++-4.9 in make/config.mk

**Comment by whizzalan** [comment]
also can't compiled with gcc4.9 & gcc5
my gcc version
as follows.
```
10116 ± gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc5/src/gcc-5.4.0/configure --prefix=/usr --build=x86_64-pc-linux-gnu --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --program-suffix=-5 --enable-version-specific-runtime-libs
Thread model: posix
gcc version 5.4.0 (GCC) 
```
myos: archlinux
cuda7.5

config.mk

```
export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS =

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /opt/cuda

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif
```
And the compile error.

```
/opt/cuda/bin/nvcc -c -o build/src/operator/correlation_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/gg/softwares/mxnet_0908/mshadow/ -I/home/gg/softwares/mxnet_0908/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=1" src/operator/correlation.cu
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o io.o src/io.cc
/opt/cuda/bin/nvcc -c -o build/src/operator/elementwise_binary_scalar_op_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/gg/softwares/mxnet_0908/mshadow/ -I/home/gg/softwares/mxnet_0908/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=1" src/operator/elementwise_binary_scalar_op.cu
/opt/cuda/bin/nvcc -c -o build/src/operator/fully_connected_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/gg/softwares/mxnet_0908/mshadow/ -I/home/gg/softwares/mxnet_0908/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=1" src/operator/fully_connected.cu
2 errors detected in the compilation of "/tmp/tmpxft_00007a3a_00000000-7_svm_output.cpp1.ii".
Makefile:156: recipe for target 'build/src/operator/svm_output_gpu.o' failed
make: *** [build/src/operator/svm_output_gpu.o] Error 2
make: *** Waiting for unfinished jobs....
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o local_filesys.o src/io/local_filesys.cc
2 errors detected in the compilation of "/tmp/tmpxft_00007a39_00000000-7_leaky_relu.cpp1.ii".
Makefile:156: recipe for target 'build/src/operator/leaky_relu_gpu.o' failed
make: *** [build/src/operator/leaky_relu_gpu.o] Error 2
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o data.o src/data.cc
2 errors detected in the compilation of "/tmp/tmpxft_00007a31_00000000-7_ndarray_function.cpp1.ii".
Makefile:156: recipe for target 'build/src/ndarray/ndarray_function_gpu.o' failed
make: *** [build/src/ndarray/ndarray_function_gpu.o] Error 2
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio.o src/recordio.cc
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o config.o src/config.cc
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00007a70_00000000-7_correlation.cpp1.ii".
Makefile:156: recipe for target 'build/src/operator/correlation_gpu.o' failed
make: *** [build/src/operator/correlation_gpu.o] Error 2
2 errors detected in the compilation of "/tmp/tmpxft_00007a8a_00000000-7_fully_connected.cpp1.ii".
Makefile:156: recipe for target 'build/src/operator/fully_connected_gpu.o' failed
make: *** [build/src/operator/fully_connected_gpu.o] Error 2
2 errors detected in the compilation of "/tmp/tmpxft_00007a82_00000000-7_elementwise_binary_scalar_op.cpp1.ii".
Makefile:156: recipe for target 'build/src/operator/elementwise_binary_scalar_op_gpu.o' failed
make: *** [build/src/operator/elementwise_binary_scalar_op_gpu.o] Error 2
In file included from include/dmlc/data.h:16:0,
                 from src/data.cc:5:
include/dmlc/./registry.h:219:22: warning: ‘dmlc::__make_ParserFactoryReg_uint32_t_libsvm__’ defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/dmlc/data.h:303:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
   DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
   ^
src/data.cc:136:1: note: in expansion of macro ‘DMLC_REGISTER_DATA_PARSER’
 DMLC_REGISTER_DATA_PARSER(uint32_t, libsvm, data::CreateLibSVMParser<uint32_t>);
 ^
include/dmlc/./registry.h:219:22: warning: ‘dmlc::__make_ParserFactoryReg_uint64_t_libsvm__’ defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/dmlc/data.h:303:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
   DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
   ^
src/data.cc:137:1: note: in expansion of macro ‘DMLC_REGISTER_DATA_PARSER’
 DMLC_REGISTER_DATA_PARSER(uint64_t, libsvm, data::CreateLibSVMParser<uint64_t>);
 ^
include/dmlc/./registry.h:219:22: warning: ‘dmlc::__make_ParserFactoryReg_uint32_t_csv__’ defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/dmlc/data.h:303:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
   DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
   ^
src/data.cc:139:1: note: in expansion of macro ‘DMLC_REGISTER_DATA_PARSER’
 DMLC_REGISTER_DATA_PARSER(uint32_t, csv, data::CreateCSVParser<uint32_t>);
 ^
In file included from include/dmlc/./registry.h:14:0,
                 from include/dmlc/data.h:16,
                 from src/data.cc:5:
include/dmlc/././parameter.h:254:43: warning: ‘dmlc::data::__make__CSVParserParamParamManager__’ defined but not used [-Wunused-variable]
   static ::dmlc::parameter::ParamManager &__make__ ## PType ## ParamManager__ = \
                                           ^
src/data.cc:93:1: note: in expansion of macro ‘DMLC_REGISTER_PARAMETER’
 DMLC_REGISTER_PARAMETER(CSVParserParam);
 ^
ar cr libdmlc.a line_split.o recordio_split.o input_split_base.o io.o local_filesys.o data.o recordio.o config.o
make[1]: Leaving directory '/home/gg/softwares/mxnet_0908/dmlc-core'
In file included from src/operator/./elementwise_binary_broadcast_op-inl.h:40:0,
                 from src/operator/elementwise_binary_broadcast_op.cc:6:
include/mxnet/operator_util.h:481:3: warning: ‘mxnet::op::__make_SimpleOpRegEntry_broadcast_plus__XPU__’ defined but not used [-Wunused-variable]
   __make_ ## SimpleOpRegEntry ## _ ## Name ## __ ## DEV ##__ =          \
   ^
src/operator/./elementwise_binary_broadcast_op-inl.h:510:1: note: in expansion of macro ‘MXNET_REGISTER_SIMPLE_OP’
 MXNET_REGISTER_SIMPLE_OP(broadcast_plus, XPU)
 ^
include/mxnet/operator_util.h:481:3: warning: ‘mxnet::op::__make_SimpleOpRegEntry_broadcast_minus__XPU__’ defined but not used [-Wunused-variable]
   __make_ ## SimpleOpRegEntry ## _ ## Name ## __ ## DEV ##__ =          \
   ^
src/operator/./elementwise_binary_broadcast_op-inl.h:518:1: note: in expansion of macro ‘MXNET_REGISTER_SIMPLE_OP’
 MXNET_REGISTER_SIMPLE_OP(broadcast_minus, XPU)
 ^
include/mxnet/operator_util.h:481:3: warning: ‘mxnet::op::__make_SimpleOpRegEntry_broadcast_mul__XPU__’ defined but not used [-Wunused-variable]
   __make_ ## SimpleOpRegEntry ## _ ## Name ## __ ## DEV ##__ =          \
   ^
src/operator/./elementwise_binary_broadcast_op-inl.h:526:1: note: in expansion of macro ‘MXNET_REGISTER_SIMPLE_OP’
 MXNET_REGISTER_SIMPLE_OP(broadcast_mul, XPU)
 ^
include/mxnet/operator_util.h:481:3: warning: ‘mxnet::op::__make_SimpleOpRegEntry_broadcast_div__XPU__’ defined but not used [-Wunused-variable]
   __make_ ## SimpleOpRegEntry ## _ ## Name ## __ ## DEV ##__ =          \
   ^
src/operator/./elementwise_binary_broadcast_op-inl.h:533:1: note: in expansion of macro ‘MXNET_REGISTER_SIMPLE_OP’
 MXNET_REGISTER_SIMPLE_OP(broadcast_div, XPU)
 ^
include/mxnet/operator_util.h:481:3: warning: ‘mxnet::op::__make_SimpleOpRegEntry_broadcast_power__XPU__’ defined but not used [-Wunused-variable]
   __make_ ## SimpleOpRegEntry ## _ ## Name ## __ ## DEV ##__ =          \
   ^
src/operator/./elementwise_binary_broadcast_op-inl.h:540:1: note: in expansion of macro ‘MXNET_REGISTER_SIMPLE_OP’
 MXNET_REGISTER_SIMPLE_OP(broadcast_power, XPU)

```

nvidia ouptut

```
 nvidia-smi                                                                                                                                                                                               ✹
Thu Sep  8 02:01:16 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 364.19     Driver Version: 364.19         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 850M    Off  | 0000:01:00.0     Off |                  N/A |
| N/A   65C    P0    N/A /  N/A |      7MiB /  2047MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

nvcc version
```
nvcc --version                                                                                                                                                                                           ✹
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

**Comment by geraint0923** [comment]
Try [this](http://stackoverflow.com/questions/34996295/trying-to-get-cuda-7-5-to-work-with-gcc-5-x)

**Comment by whizzalan** [comment]
@geraint0923  is this using gcc 4.8?

**Comment by acgtyrant** [comment]
I use Arch Linux which has the newest CUDA 7.5 and GCC6. However, it is lucky that the official packaged GCC5(it also offers gcc4.9 actually), so I installed gcc5 and change config.mk:

```
export CC = gcc-4.9
export CXX = g++-4.9
```

And because of archlinux's OpenCV is compiled by GCC6, so we cannot link it immediately, change `USE_OPENCV` to `0`.

I compiled MXNet without OpenCV successfully...

**Comment by whizzalan** [comment]
@acgtyrant  thank you for this message.
I compile with cuda 7.0 and gcc5, it's worked.

**Comment by acgtyrant** [comment]
I find that CUDA 8 is released already! I installed it and update all software to newest, now I can confirm that MXNet can be compiled with GCC 6 and CUDA 8 in Arch Linux.

**Comment by jingpengwu** [comment]
I am using intel mkl 2017, but got some compilation errors.

```
In file included from src/operator/mkl/mkl_cppwrapper.cc(25):                                [30/1983]│················
src/operator/mkl/mkl_cppwrapper.h(833): error: identifier "dnnBatchNormalizationCreateForward_v2_F32" │················
is undefined                                                                                          │················
      return dnnBatchNormalizationCreateForward_v2_F32(                                               │················
             ^                                                                                        │················
                                                                                                      │················
In file included from src/operator/mkl/mkl_cppwrapper.cc(25):                                         │················
src/operator/mkl/mkl_cppwrapper.h(843): error: identifier "dnnBatchNormalizationCreateForward_v2_F64" │················
is undefined                                                                                          │················
      return dnnBatchNormalizationCreateForward_v2_F64(                                               │················
             ^                                                                                        │················
                                                                                                      │················
In file included from src/operator/mkl/mkl_cppwrapper.cc(25):                                         │················
src/operator/mkl/mkl_cppwrapper.h(861): error: identifier "dnnBatchNormalizationCreateBackward_v2_F32"│················
 is undefined                                                                                         │················
      return dnnBatchNormalizationCreateBackward_v2_F32(                                              │················
             ^                                                                                        │················
                                                                                                      │················
In file included from src/operator/mkl/mkl_cppwrapper.cc(25):                                         │················
src/operator/mkl/mkl_cppwrapper.h(872): error: identifier "dnnBatchNormalizationCreateBackward_v2_F64"│················
 is undefined                                                                                         │················
      return dnnBatchNormalizationCreateBackward_v2_F64(                                              │················
             ^                                                                                        │················
                                                                                                      │················
compilation aborted for src/operator/mkl/mkl_cppwrapper.cc (code 2)                                   │················
Makefile:202: recipe for target 'build/src/operator/mkl/mkl_cppwrapper.o' failed                      │················
icpc: command line warning #10006: ignoring unknown option '-Wno-unused-local-typedefs'               │················
make: *** [build/src/operator/mkl/mkl_cppwrapper.o] Error 2                                           │················
make: *** Waiting for unfinished jobs....                                                             │················
icpc: command line warning #10006: ignoring unknown option '-Wno-unused-local-typedefs'               │················
icpc: command line warning #10006: ignoring unknown option '-Wno-unused-local-typedefs'               │················
icpc: command line warning #10006: ignoring unknown option '-Wno-unused-local-typedefs'               │················
icpc: command line warning #10006: ignoring unknown option '-Wno-unused-local-typedefs'               │················
In file included from src/operator/mkl/mkl_memory-inl.h(29),                                          │················
                 from src/operator/mkl/mkl_memory.cc(26):      

compilation aborted for src/operator/mkl/mkl_memory.cc (code 2)                                       │················
Makefile:202: recipe for target 'build/src/operator/mkl/mkl_memory.o' failed                          │················
make: *** [build/src/operator/mkl/mkl_memory.o] Error 2                  
```

**Comment by juicedatom** [comment]
@acgtyrant So, did you end up compiling mxnet with GCC6 and cuda 8? what did you have to change?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
