### ISSUE TITLE
Installation instructions MacOS/R/CPU don't work.

### ISSUE THREAD

**Issue by pwn1** [apache/incubator-mxnet#11098]
## Description
(Brief description of the problem in no more than 2 sentences.)

Doing the installation exactly as indicated on the website does not work -- fails with 404 Not Found error.

## Environment info (Required)

----------Python Info----------
('Version      :', '2.7.15')
('Compiler     :', 'GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)')
('Build        :', ('default', 'May  1 2018 16:44:08'))
('Arch         :', ('64bit', ''))
------------Pip Info-----------
('Version      :', '10.0.1')
('Directory    :', '/usr/local/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Darwin-17.5.0-x86_64-i386-64bit')
('system       :', 'Darwin')
('node         :', '8afbcfb5.cs.st-andrews.ac.uk')
('release      :', '17.5.0')
('version      :', 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'i386')
machdep.cpu.brand_string: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID FPU_CSDS
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT RDTSCP TSCI
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0013 sec, LOAD: 1.0522 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0137 sec, LOAD: 0.4825 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0147 sec, LOAD: 0.7350 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0465 sec, LOAD: 0.0671 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1305 sec, LOAD: 0.7929 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0606 sec, LOAD: 0.7719 sec.

Package used (Python/R/Scala/Julia):
R

For R user, please provide R `sessionInfo()`:
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] palm_1.1.0          mvtnorm_1.0-7       twoplane_1.0        functional_0.6      HiddenMarkov_1.8-11 expm_0.999-2       
[7] Matrix_1.2-14       boot_1.3-20         Rcpp_0.12.16       

loaded via a namespace (and not attached):
 [1] magic_1.5-8          ddalpha_1.3.2        tidyr_0.8.0          sfsmisc_1.1-2        splines_3.5.0       
 [6] foreach_1.4.4        prodlim_2018.04.18   assertthat_0.2.0     stats4_3.5.0         DRR_0.0.3           
[11] robustbase_0.93-0    ipred_0.9-6          pillar_1.2.2         lattice_0.20-35      glue_1.2.0          
[16] polyclip_1.6-1       minqa_1.2.4          colorspace_1.3-2     recipes_0.1.2        plyr_1.8.4          
[21] psych_1.8.3.3        timeDate_3043.102    pkgconfig_2.0.1      CVST_0.2-1           broom_0.4.4         
[26] caret_6.0-79         purrr_0.2.4          scales_0.5.0         tensor_1.5           gower_0.1.2         
[31] lava_1.6.1           spatstat.utils_1.8-0 tibble_1.4.2         mgcv_1.8-23          ggplot2_2.2.1       
[36] withr_2.1.2          nnet_7.3-12          lazyeval_0.2.1       mnormt_1.5-5         survival_2.41-3     
[41] magrittr_1.5         deldir_0.1-15        nlme_3.1-137         MASS_7.3-49          gsl_1.9-10.3        
[46] dimRed_0.1.0         foreign_0.8-70       class_7.3-14         tools_3.5.0          stringr_1.3.0       
[51] kernlab_0.9-25       munsell_0.4.3        bindrcpp_0.2.2       compiler_3.5.0       RcppRoll_0.2.2      
[56] rlang_0.2.0          grid_3.5.0           iterators_1.0.9      goftest_1.1-1        geometry_0.3-6      
[61] gtable_0.2.0         ModelMetrics_1.1.0   codetools_0.2-15     abind_1.4-5          reshape2_1.4.3      
[66] R6_2.2.2             lubridate_1.7.4      dplyr_0.7.4          bindr_0.1.1          stringi_1.1.7       
[71] spatstat.data_1.2-0  parallel_3.5.0       spatstat_1.55-1      rpart_4.1-13         DEoptimR_1.0-8      
[76] tidyselect_0.2.4  

## Steps to reproduce
On R terminal:

> cran <- getOption("repos")
> cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
> options(repos = cran)
> install.packages("mxnet")
Warning in install.packages :
  unable to access index for repository https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/macosx/el-capitan/contrib/3.5:
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/bin/macosx/el-capitan/contrib/3.5/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘mxnet’
Do you want to attempt to install these from sources? (Yes/no/cancel) Yes
installing the source package ‘mxnet’

trying URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz'
Warning in install.packages :
  download of package ‘mxnet’ failed

**Comment by anirudhacharya** [comment]
can you try the following link - ``install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)``

@eric-haibin-lin please label this - "R", "Installation"

**Comment by pwn1** [comment]
Thanks for quick response.
Here's the output:

> install.packages("https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip", repos = NULL)
trying URL 'https://s3.ca-central-1.amazonaws.com/jeremiedb/share/mxnet/CPU/mxnet.zip'
Content type 'application/zip' length 29016598 bytes (27.7 MB)
==================================================
downloaded 27.7 MB

Error in install.packages : type == "both" cannot be used with 'repos = NULL'

**Comment by onlyphantom** [comment]
Wondering if anyone got it to work on R 3.5.0 on mac OS? The lack of responses or support for mac / linux users is concerning

**Comment by anirudhacharya** [comment]
@onlyphantom @pwn1  I was able to build the R bindings from source and the created tar is [here](https://github.com/anirudhacharya/MLProjects/blob/master/mxnet_1.3.0.tar.gz) 
you can install it using the command ``R CMD install mxnet_1.3.0.tar.gz``

You can check [this page](https://github.com/jeremiedb/mxnet_winbin) for installing binaries for Windows.

**Comment by cscheeder** [comment]
@anirudhacharya ... following your instructions I get an opencv2 related error:
`im2rec.cc:20:10: fatal error: 'opencv2/opencv.hpp' file not found
#include <opencv2/opencv.hpp>
`
Thanks

**Comment by pwn1** [comment]
I also followed your instructions @anirudhacharya and got the same opencv error.  I installed opencv using homebrew, then I get the following:

`im2rec.cc:21:10: fatal error: 'image_recordio.h' file not found
#include "image_recordio.h"`

**Comment by onlyphantom** [comment]
Thanks for the reply @anirudh2290 ; No luck as the two other users above stated; For now I switched back to R 3.4 (re-install MXNet under R3.4 doesn't seem to be a problem) to be able to continue using MXNet, but when a fix is submitted I'll be happy to try again!

**Comment by jimhester** [comment]
In order to use the mxnet cpu binary available at https://mxnet.incubator.apache.org/install/index.html?platform=MacOS&language=R&processor=CPU I needed to compile opencv with `opencv_hdf` and `opencv_text` support (which is not the default for the homebrew bottle currently).

```diff
diff --git a/Formula/opencv.rb b/Formula/opencv.rb
index 1ac968d75e..1a7f05c92a 100644
--- a/Formula/opencv.rb
+++ b/Formula/opencv.rb
@@ -56,9 +56,9 @@ class Opencv < Formula
       -DBUILD_TESTS=OFF
       -DBUILD_TIFF=OFF
       -DBUILD_ZLIB=OFF
-      -DBUILD_opencv_hdf=OFF
+      -DBUILD_opencv_hdf=ON
       -DBUILD_opencv_java=OFF
-      -DBUILD_opencv_text=OFF
+      -DBUILD_opencv_text=ON
       -DOPENCV_ENABLE_NONFREE=ON
       -DOPENCV_EXTRA_MODULES_PATH=#{buildpath}/opencv_contrib/modules
       -DWITH_1394=OFF
```

Then it can be installed with the following and the library can be loaded.

```shell
brew install opencv --build-from-source
```

**Comment by hetong007** [comment]
@jimhester Good to know that you've figured it out. 

The `mxnet` package has just been updated yesterday with 3.5.1, and avoided including unnecessary dependencies on opencv contribs. So now a simple `brew install opencv` should work as well.

**Comment by sandeep-krishnamurthy** [comment]
Resolving as issue is fixed. Please reopen if you encounter the issue.

**Comment by rfarahmand** [comment]
I still have problem Installing MXNet from source on OS X (macOS high Sierra). It seems it cannot find opencv2; but I have installed using `brew install opencv` I even tried compiling from source as recommended above - no luck. I get the error below:
  
`
In file included from src/operator/image/crop.cc:27:
In file included from src/operator/image/crop-inl.h:35:
src/operator/image/image_utils.h:32:12: fatal error: 'opencv2/opencv.hpp' file not found
  #include <opencv2/opencv.hpp>
           ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/src/operator/image/crop.o] Error 1
make: *** Waiting for unfinished jobs....
MacBook-Pro-75:mxnet rfarahmand$ brew search opencv
==> Formulae
opencv ✔                                                             opencv@2 ✔                                                           opencv@3 ✔
`
