### ISSUE TITLE
AttributeError: module 'mxnet.ndarray._internal' has no attribute '_rnn_param_concat'

### ISSUE THREAD

**Issue by Marcovaldong** [apache/incubator-mxnet#15091]
My code was ok when using MxNet v1.1.0. When I upgrade it to v1.4.0, I got the current error when using lstm: 

```
Traceback (most recent call last):
  File "train3.py", line 271, in <module>
    train()
  File "train3.py", line 217, in train
    loss = model(xs, ys, xlen, ylen)
  File "/disk2/dongsq/incubator-mxnet/python/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/disk2/dongsq/my/RNNT-Transducer/model.py", line 526, in forward
    f = self.encoder(xs)
  File "/disk2/dongsq/incubator-mxnet/python/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/disk2/dongsq/my/RNNT-Transducer/model.py", line 107, in forward
    h = self.rnn(xs)
  File "/disk2/dongsq/incubator-mxnet/python/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/disk2/dongsq/incubator-mxnet/python/mxnet/gluon/block.py", line 917, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/disk2/dongsq/incubator-mxnet/python/mxnet/gluon/rnn/rnn_layer.py", line 234, in hybrid_forward
    out = self._forward_kernel(F, inputs, states, **kwargs)
  File "/disk2/dongsq/incubator-mxnet/python/mxnet/gluon/rnn/rnn_layer.py", line 257, in _forward_kernel
    params = F._internal._rnn_param_concat(*params, dim=0)
AttributeError: module 'mxnet.ndarray._internal' has no attribute '_rnn_param_concat'
```

How can I fix it? Or should I upgrade it to newest version?

**Comment by frankfliu** [comment]
@mxnet-label-bot add [question]

**Comment by Marcovaldong** [comment]
@szha Is there any one who got this error?

**Comment by szha** [comment]
@Marcovaldong this sounds like an issue where the python code was upgraded but the libmxnet.so was not. Looks like you're building from source. Could you try rebuild? To make sure the code is up-to-date:
```
git submodule update --init --recursive
make clean
```

**Comment by Marcovaldong** [comment]
@szha Yes, there are two version MxNet in my environments. I upgrade the python code and update the environment variables, but forgot to source them. 

Thanks for your reply, I fixed it.
