### ISSUE TITLE
same train code, 0.8.0 is 4 times faster than 0.9.5

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#6299]
my training code:
use mxnetv0.8.0:
Speed: 377.82 samples/sec

but when use mxnetv0.9.5:
Speed: 90.0 samples/sec

environment:
```python
kvstore='device'
```
or
```python
kvstore=None
```
actually, the following env variable doesn't matter.
```bash
export MXNET_ENABLE_GPU_P2P=0
export MXNET_CUDNN_AUTOTUNE_DEFAULT=0
```

and in mxnet 0.9.5, my training cost is same whenever setting ```kvstore='local'``` or ```kvstore='device'```

@piiswrong 
@reminisce

**Comment by piiswrong** [comment]
please post network definition

**Comment by starimpact** [comment]
```python
def ConvFactory(data, num_filter, kernel, stride=(1, 1), pad=(0, 0), act_type="relu", mirror_attr={}, with_act=True, namepre='', args=None):
  if args is None:
    weight = mx.sym.Variable(namepre+'_weight')
    bias = mx.sym.Variable(namepre+'_bias')
    gamma = mx.sym.Variable(namepre+'_gamma')
    beta = mx.sym.Variable(namepre+'_beta')
    args = {'weight':weight, 'bias':bias}
  else:
    weight = args['weight']
    bias = args['bias']
    gamma = args['gamma']
    beta = args['beta']
  
  conv = mx.symbol.Convolution(data=data, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad, weight=weight, bias=bias, name=namepre+'_conv')
  bn = mx.symbol.BatchNorm(data=conv, gamma=gamma, beta=beta, name=namepre+'_bn')
  act = bn
  if with_act:
      act = mx.symbol.Activation(data=bn, act_type=act_type, attr=mirror_attr, name=namepre+'_act')
  return act, args


def stem(data, namepre='', args=None):
  if args is None:
    args = {'conv1a_3_3':None, 'conv2a_3_3':None, 'conv2b_3_3':None, 'conv3b_1_1':None, 'conv4a_3_3':None}
  conv1a_3_3, args['conv1a_3_3'] = ConvFactory(data=data, num_filter=32,
                           kernel=(3, 3), stride=(2, 2), namepre=namepre+'_conv1a_3_3', args=args['conv1a_3_3'])
  conv2a_3_3, args['conv2a_3_3'] = ConvFactory(conv1a_3_3, 32, (3, 3), namepre=namepre+'_conv2a_3_3', args=args['conv2a_3_3'])
  conv2b_3_3, args['conv2b_3_3'] = ConvFactory(conv2a_3_3, 64, (3, 3), pad=(1, 1), namepre=namepre+'_conv2b_3_3', args=args['conv2b_3_3'])
  maxpool3a_3_3 = mx.symbol.Pooling(
      data=conv2b_3_3, kernel=(3, 3), stride=(2, 2), pool_type='max', name=namepre+'_maxpool3a_3_3')
  conv3b_1_1, args['conv3b_1_1'] = ConvFactory(maxpool3a_3_3, 80, (1, 1), namepre=namepre+'_conv3b_1_1', args=args['conv3b_1_1'])
  conv4a_3_3, args['conv4a_3_3'] = ConvFactory(conv3b_1_1, 192, (3, 3), namepre=namepre+'_conv4a_3_3', args=args['conv4a_3_3'])

  return conv4a_3_3, args 


def reductionA(conv4a_3_3, namepre='', args=None):
  if args is None:
    args = {'tower_conv':None, 'tower_conv1_0':None, 'tower_conv1_1':None, 'tower_conv2_0':None, 'tower_conv2_1':None, 'tower_conv2_2':None, 'tower_conv3_1':None}
  maxpool5a_3_3 = mx.symbol.Pooling(
      data=conv4a_3_3, kernel=(3, 3), stride=(2, 2), pool_type='max', name=namepre+'_maxpool5a_3_3')

  tower_conv, args['tower_conv'] = ConvFactory(maxpool5a_3_3, 96, (1, 1), namepre=namepre+'_tower_conv', args=args['tower_conv'])
  tower_conv1_0, args['tower_conv1_0'] = ConvFactory(maxpool5a_3_3, 48, (1, 1), namepre=namepre+'_tower_conv1_0', args=args['tower_conv1_0'])
  tower_conv1_1, args['tower_conv1_1'] = ConvFactory(tower_conv1_0, 64, (5, 5), pad=(2, 2), namepre=namepre+'_tower_conv1_1', args=args['tower_conv1_1'])

  tower_conv2_0, args['tower_conv2_0'] = ConvFactory(maxpool5a_3_3, 64, (1, 1), namepre=namepre+'_tower_conv2_0', args=args['tower_conv2_0'])
  tower_conv2_1, args['tower_conv2_1'] = ConvFactory(tower_conv2_0, 96, (3, 3), pad=(1, 1), namepre=namepre+'_tower_conv2_1', args=args['tower_conv2_1'])
  tower_conv2_2, args['tower_conv2_2'] = ConvFactory(tower_conv2_1, 96, (3, 3), pad=(1, 1), namepre=namepre+'_tower_conv2_2', args=args['tower_conv2_2'])

  tower_pool3_0 = mx.symbol.Pooling(data=maxpool5a_3_3, kernel=(
      3, 3), stride=(1, 1), pad=(1, 1), pool_type='avg', name=namepre+'_tower_pool3_0')
  tower_conv3_1, args['tower_conv3_1'] = ConvFactory(tower_pool3_0, 64, (1, 1), namepre=namepre+'_tower_conv3_1', args=args['tower_conv3_1'])
  tower_5b_out = mx.symbol.Concat(
      *[tower_conv, tower_conv1_1, tower_conv2_2, tower_conv3_1])
  return tower_5b_out, args 


def reductionB(net, namepre='', args=None):
  if args is None:
    args = {'tower_conv':None, 'tower_conv1_0':None, 'tower_conv1_1':None, 'tower_conv1_2':None}
  tower_conv, args['tower_conv'] = ConvFactory(net, 384, (3, 3), stride=(2, 2), namepre=namepre+'_tower_conv', args=args['tower_conv'])
  tower_conv1_0, args['tower_conv1_0'] = ConvFactory(net, 256, (1, 1), namepre=namepre+'_tower_conv1_0', args=args['tower_conv1_0'])
  tower_conv1_1, args['tower_conv1_1'] = ConvFactory(tower_conv1_0, 256, (3, 3), pad=(1, 1), namepre=namepre+'_tower_conv1_1', args=args['tower_conv1_1'])
  tower_conv1_2, args['tower_conv1_2'] = ConvFactory(tower_conv1_1, 384, (3, 3), stride=(2, 2), namepre=namepre+'_tower_conv1_2', args=args['tower_conv1_2'])
  tower_pool = mx.symbol.Pooling(net, kernel=(
      3, 3), stride=(2, 2), pool_type='max', name=namepre+'_tower_pool')
  net = mx.symbol.Concat(*[tower_conv, tower_conv1_2, tower_pool])

  return net, args


def reductionC(net, namepre='', args=None):
  if args is None:
    args = {'tower_conv':None, 'tower_conv0_1':None, 'tower_conv1':None, 'tower_conv1_1':None, 'tower_conv2':None, 'tower_conv2_1':None, 'tower_conv2_2':None}
  tower_conv, args['tower_conv'] = ConvFactory(net, 256, (1, 1), namepre=namepre+'_tower_conv', args=args['tower_conv'])
  tower_conv0_1, args['tower_conv0_1'] = ConvFactory(tower_conv, 384, (3, 3), stride=(2, 2), namepre=namepre+'_tower_conv0_1', args=args['tower_conv0_1'])
  tower_conv1, args['tower_conv1'] = ConvFactory(net, 256, (1, 1), namepre=namepre+'_tower_conv1', args=args['tower_conv1'])
  tower_conv1_1, args['tower_conv1_1'] = ConvFactory(tower_conv1, 288, (3, 3), stride=(2, 2), namepre=namepre+'_tower_conv1_1', args=args['tower_conv1_1'])
  tower_conv2, args['tower_conv2'] = ConvFactory(net, 256, (1, 1), namepre=namepre+'_tower_conv2', args=args['tower_conv2'])
  tower_conv2_1, args['tower_conv2_1'] = ConvFactory(tower_conv2, 288, (3, 3), pad=(1, 1), namepre=namepre+'_tower_conv2_1', args=args['tower_conv2_1'])
  tower_conv2_2, args['tower_conv2_2'] = ConvFactory(tower_conv2_1, 320, (3, 3),  stride=(2, 2), namepre=namepre+'_tower_conv2_2', args=args['tower_conv2_2'])
  tower_pool = mx.symbol.Pooling(net, kernel=(3, 3), stride=(2, 2), pool_type='max', name=namepre+'_tower_pool')
  net = mx.symbol.Concat(*[tower_conv0_1, tower_conv1_1, tower_conv2_2, tower_pool])
  return net, args


def block35(net, input_num_channels, scale=1.0, with_act=True, act_type='relu', mirror_attr={}, namepre='', args=None):
  if args is None:
    args = {'tower_conv':None, 'tower_conv1_0':None, 'tower_conv1_1':None, 'tower_conv2_0':None, 'tower_conv2_1':None, 'tower_conv2_2':None, 'tower_out':None}
  tower_conv, args['tower_conv'] = ConvFactory(net, 32, (1, 1), namepre=namepre+'_tower_conv', args=args['tower_conv'])
  tower_conv1_0, args['tower_conv1_0'] = ConvFactory(net, 32, (1, 1), namepre=namepre+'_tower_conv1_0', args=args['tower_conv1_0'])
  tower_conv1_1, args['tower_conv1_1'] = ConvFactory(tower_conv1_0, 32, (3, 3), pad=(1, 1), namepre=namepre+'_tower_conv1_1', args=args['tower_conv1_1'])
  tower_conv2_0, args['tower_conv2_0'] = ConvFactory(net, 32, (1, 1), namepre=namepre+'_tower_conv2_0', args=args['tower_conv2_0'])
  tower_conv2_1, args['tower_conv2_1'] = ConvFactory(tower_conv2_0, 48, (3, 3), pad=(1, 1), namepre=namepre+'_tower_conv2_1', args=args['tower_conv2_1'])
  tower_conv2_2, args['tower_conv2_2'] = ConvFactory(tower_conv2_1, 64, (3, 3), pad=(1, 1), namepre=namepre+'_tower_conv2_2', args=args['tower_conv2_2'])
  tower_mixed = mx.symbol.Concat(*[tower_conv, tower_conv1_1, tower_conv2_2])
  tower_out, args['tower_out'] = ConvFactory(
      tower_mixed, input_num_channels, (1, 1), with_act=False, namepre=namepre+'_tower_out', args=args['tower_out'])

  net += scale * tower_out
  act = net
  if with_act:
      act = mx.symbol.Activation(
          data=net, act_type=act_type, attr=mirror_attr, name=namepre+'_act')
  return act, args


def block17(net, input_num_channels, scale=1.0, with_act=True, act_type='relu', mirror_attr={}, namepre='', args=None):
  if args is None:
    args = {'tower_conv':None, 'tower_conv1_0':None, 'tower_conv1_1':None, 'tower_conv1_2':None, 'tower_out':None}
  tower_conv, args['tower_conv'] = ConvFactory(net, 192, (1, 1), namepre=namepre+'_tower_conv', args=args['tower_conv'])
  tower_conv1_0, args['tower_conv1_0'] = ConvFactory(net, 129, (1, 1), namepre=namepre+'_tower_conv1_0', args=args['tower_conv1_0'])
  tower_conv1_1, args['tower_conv1_1'] = ConvFactory(tower_conv1_0, 160, (1, 7), pad=(1, 2), namepre=namepre+'_tower_conv1_1', args=args['tower_conv1_1'])
  tower_conv1_2, args['tower_conv1_2'] = ConvFactory(tower_conv1_1, 192, (7, 1), pad=(2, 1), namepre=namepre+'_tower_conv1_2', args=args['tower_conv1_2'])
  tower_mixed = mx.symbol.Concat(*[tower_conv, tower_conv1_2])
  tower_out, args['tower_out'] = ConvFactory(
      tower_mixed, input_num_channels, (1, 1), with_act=False, namepre=namepre+'_tower_out', args=args['tower_out'])
  net += scale * tower_out
  act = net
  if with_act:
      act = mx.symbol.Activation(
          data=net, act_type=act_type, attr=mirror_attr, name=namepre+'_act')
  return act, args


def block8(net, input_num_channels, scale=1.0, with_act=True, act_type='relu', mirror_attr={}, namepre='', args=None):
  if args is None:
    args = {'tower_conv':None, 'tower_conv1_0':None, 'tower_conv1_1':None, 'tower_conv1_2':None, 'tower_out':None}
  tower_conv, args['tower_conv'] = ConvFactory(net, 192, (1, 1), namepre=namepre+'_tower_conv', args=args['tower_conv'])
  tower_conv1_0, args['tower_conv1_0'] = ConvFactory(net, 192, (1, 1), namepre=namepre+'_tower_conv1_0', args=args['tower_conv1_0'])
  tower_conv1_1, args['tower_conv1_1'] = ConvFactory(tower_conv1_0, 224, (1, 3), pad=(0, 1), namepre=namepre+'_tower_conv1_1', args=args['tower_conv1_1'])
  tower_conv1_2, args['tower_conv1_2'] = ConvFactory(tower_conv1_1, 256, (3, 1), pad=(1, 0), namepre=namepre+'_tower_conv1_2', args=args['tower_conv1_2'])
  tower_mixed = mx.symbol.Concat(*[tower_conv, tower_conv1_2])
  tower_out, args['tower_out'] = ConvFactory(
      tower_mixed, input_num_channels, (1, 1), with_act=False, namepre=namepre+'_tower_out', args=args['tower_out'])
  net += scale * tower_out
  act = net
  if with_act:
      act = mx.symbol.Activation(
          data=net, act_type=act_type, attr=mirror_attr, name=namepre+'_act')
  return act, args


def repeat(inputs, repetitions, layer, *ltargs, **kwargs):
  outputs = inputs
  namepre = kwargs['namepre']
  args = kwargs['args']
  if args is None:
    args = {}
    for i in xrange(repetitions):
      argname='repeat_'+str(i)
      args[argname] = None
  for i in range(repetitions):
    kwargs['namepre'] = namepre+'_'+str(i)
    argname='repeat_'+str(i)
    kwargs['args'] = args[argname]
#    print ltargs
#    print kwargs
    outputs, args[argname] = layer(outputs, *ltargs, **kwargs)

  return outputs, args


def create_inception_resnet_v2(data, namepre='', args=None):
  if args is None:
    args = {'stem':None, 'reductionA':None, 'repeat_block35':None, 'reductionB':None, 
            'repeat_block17':None, 'reductionC':None, 'repeat_block8':None, 
            'final_block8':None, 'final_conv':None, 'finalfc':None}

  stem_net, args['stem']= stem(data, namepre=namepre+'_stem', args=args['stem'])

  reduceA, args['reductionA'] = reductionA(stem_net, namepre=namepre+'_reductionA', args=args['reductionA'])

  repeat_block35, args['repeat_block35'] = repeat(reduceA, 1, block35, scale=0.17, input_num_channels=320, namepre=namepre+'_repeat_block35', args=args['repeat_block35'])


  reduceB, args['reductionB'] = reductionB(repeat_block35, namepre=namepre+'_reductionB', args=args['reductionB'])

  repeat_block17, args['repeat_block17'] = repeat(reduceB, 2, block17, scale=0.1, input_num_channels=1088, namepre=namepre+'_repeat_block17', args=args['repeat_block17'])

  reduceC, args['reductionC'] = reductionC(repeat_block17, namepre=namepre+'_reductionC', args=args['reductionC'])

  repeat_block8, args['repeat_block8'] = repeat(reduceC, 1, block8, scale=0.2, input_num_channels=2080, namepre=namepre+'_repeat_block8', args=args['repeat_block8'])
  final_block8, args['final_block8'] = block8(repeat_block8, with_act=False, input_num_channels=2080, namepre=namepre+'_final_block8', args=args['final_block8'])

  final_conv, args['final_conv'] = ConvFactory(final_block8, 1536, (1, 1), namepre=namepre+'_final_conv', args=args['final_conv'])
  final_pool = mx.symbol.Pooling(final_conv, kernel=(8, 8), stride=(1, 1), pool_type='avg', name=namepre+'_final_pool')
  final_flatten = mx.symbol.Flatten(final_pool, name=namepre+'_final_flatten')

  drop1 = mx.sym.Dropout(data=final_flatten, p=0.5, name=namepre+'_dropout1')

  if args['finalfc'] is None:
    args['finalfc'] = {}
    args['finalfc']['weight'] = mx.sym.Variable(namepre+'_fc1_weight')
    args['finalfc']['bias'] = mx.sym.Variable(namepre+'_fc1_bias')
    
  reid_fc1 = mx.sym.FullyConnected(data=drop1, num_hidden=128, name=namepre+"_fc1", 
                                   weight=args['finalfc']['weight'], bias=args['finalfc']['bias']) 
#  reid_act = mx.sym.Activation(data=reid_fc1, act_type='tanh', name=namepre+'_fc1_relu')

  net = reid_fc1

  return net, args

```

**Comment by piiswrong** [comment]
what's your IO pipeline?

**Comment by piiswrong** [comment]
It would be helpful if you can locate the commit that caused the regression with git bisect

**Comment by starimpact** [comment]
what's the ```git bisect```?

**Comment by starimpact** [comment]
my io pipeline is very normal, read data into network, and get the output.

**Comment by piiswrong** [comment]
Does the slow down happen if you feed dummy data with iterator like this:
```

class DummyIter(mx.io.DataIter):
    def __init__(self, batch_size, data_shape):
        self.data_shape = (batch_size,) + data_shape
        self.label_shape = (batch_size,)
        self.provide_data = [('data', self.data_shape)]
        self.provide_label = [('softmax_label', self.label_shape)]

    def next(self):
        return mx.io.DataBatch(data=[mx.nd.zeros(self.data_shape)],
                               label=[mx.nd.zeros(self.label_shape)])
```

**Comment by piiswrong** [comment]
https://git-scm.com/docs/git-bisect git bisect

**Comment by starimpact** [comment]
```python
459   def next(self):
460     if self.cur_batch < self.num_batches:
461 #      datas, labels, carids, infos = dg.get_data_label_proxy_batch_mxnet(self._provide_data, self._provide_label, self.proxy_datalist, self.cur_batch) 
462       datas, labels, carids, infos = dg.get_data_label_proxy_batch_mxnet_threads(self._provide_data, self.datas_batch, self._provide_label, self.labels_batch, self.proxy_datalist, self.cur_batch, self.caridnum)
463       self.batch_carids = carids
464       self.batch_infos = infos
465       self.cur_batch += 1
466       return mx.io.DataBatch(datas, labels)
467     else:
468       raise StopIteration

```

**Comment by starimpact** [comment]
strange, when I use dummy data, the speed is increased.
why?

**Comment by piiswrong** [comment]
something is wrong with your data pipeline. I don't know how mxnet version affects it.
If you can locate the commit that caused this with git bisect it would be helpful

**Comment by starimpact** [comment]
ok, I will have a try.
but ,can you tell me how the data pipeline can affect the training. I think the data reading and augmentation with threads  can't be have any relationship with forward-backward.

**Comment by starimpact** [comment]
git bisect will compare the 0.9.5 with 0.8.0, there are so many difference between the two versions.how is it possible for me to find which commit caused the problem.

**Comment by piiswrong** [comment]
its binary search.
There are about 500 commits between 0.9.5 and 0.8.0 so it will take about 9 trials to locate the commit. Not that hard

**Comment by starimpact** [comment]
ok, I will have a try.

**Comment by starimpact** [comment]
before commits of ```3e0210b1aefdc621778491bf82ccf7ad30ec3d77``` cant not be tested, because compilation error, such as 
```build/src/symbol/graph_memory_allocator.o: In function `mxnet::GraphStorageAllocator::Get(long, mxnet::TShape)':
graph_memory_allocator.cc:(.text+0x6da): undefined reference to `mxnet::GraphStorageAllocator::kBadStorageID'
```
```
git bisect start
# bad: [46782c3fd77d0b9f521270d883e35e39f7669c15] Fix typos and correct syntax for several examples. (#6293)
git bisect bad 46782c3fd77d0b9f521270d883e35e39f7669c15
# good: [67bee197702581c0c8ed9585dc24143c4cbccb8e]      [RELEASE] v0.8 Release (Last release before NNVM refactor (#4409)
git bisect good 67bee197702581c0c8ed9585dc24143c4cbccb8e
# bad: [790883106fa924d4198a31f8e09e45a6634dc263] float16 training for resnet (#5312)
git bisect bad 790883106fa924d4198a31f8e09e45a6634dc263
# bad: [790883106fa924d4198a31f8e09e45a6634dc263] float16 training for resnet (#5312)
git bisect bad 790883106fa924d4198a31f8e09e45a6634dc263
# bad: [e482d7e5d389bbc1dc3c65d3cb2a398cac3edbe7] Update neural art tutorial (#4677)
git bisect bad e482d7e5d389bbc1dc3c65d3cb2a398cac3edbe7
# bad: [c4113f3decefd1f2c6d504fa9e27adb49255115f] 0.9 release note (#4293)
git bisect bad c4113f3decefd1f2c6d504fa9e27adb49255115f
# bad: [a73afabc001b98d64675b23e1b651c8d3eff56c4] Nnvm scala fix (#3590)
git bisect bad a73afabc001b98d64675b23e1b651c8d3eff56c4
# bad: [dfe1db54e7d81872989f8748369693d59cbdf380] fix image io
git bisect bad dfe1db54e7d81872989f8748369693d59cbdf380
# bad: [b261bc9a6c7ad3535758aebb9d467784d1b984f4] update nnvm version (#3290)
git bisect bad b261bc9a6c7ad3535758aebb9d467784d1b984f4
# bad: [b2d222c0eda85df9167f38f557a18141aaac6aac] [scala] link libnnvm.a (#3214)
git bisect bad b2d222c0eda85df9167f38f557a18141aaac6aac
# bad: [3e0210b1aefdc621778491bf82ccf7ad30ec3d77] forward test
git bisect bad 3e0210b1aefdc621778491bf82ccf7ad30ec3d77
# bad: [65467228e514f22d500ad82cc80ebb5fa076d76d] refactor test util
git bisect bad 65467228e514f22d500ad82cc80ebb5fa076d76d
# bad: [04f49aace27a4f16d19cbea6afead7f4b070318c] Update kvstore_dist.h (#4413)
git bisect bad 04f49aace27a4f16d19cbea6afead7f4b070318c
# first bad commit: [04f49aace27a4f16d19cbea6afead7f4b070318c] Update kvstore_dist.h (#4413)
```

**Comment by starimpact** [comment]
@piiswrong 
@reminisce

**Comment by eric-haibin-lin** [comment]
For kBadStorageID, you can just add an extra line before that line:
Const int kBadStorageID = 1;


On 2017年5月17日, at 19:03, Zhang Ming <notifications@github.com> wrote:

kBadStorageID

**Comment by piiswrong** [comment]
You need to git submodule update after checking out a commit


Zhang Ming <notifications@github.com>于2017年5月17日 周三下午7:04写道：

**Comment by piiswrong** [comment]
Are you sure 04f49aace27a4f16d19cbea6afead7f4b070318c is a bad commit? It's directly after 0.8 release and didn't change anything related to speed

**Comment by piiswrong** [comment]
I suspect its this one: https://github.com/dmlc/mxnet/commit/9203e3857d05ae982907c75c894668047c51d4a8
see if reverting it helps

**Comment by eric-haibin-lin** [comment]
I remember lstm (without bulk) is much slower in the first nnvm release compared to 0.8 (also without bulk) 

On 2017年5月17日, at 21:05, Eric Junyuan Xie <notifications@github.com> wrote:

I suspect its this one: 9203e38
see if reverting it helps

**Comment by starimpact** [comment]
@piiswrong ok, I will do another try with ```git submodules update```.

**Comment by starimpact** [comment]
when I bisect to ```b261bc9a6c7ad3535758aebb9d467784d1b984f4```, can not compile:
```
src/nnvm/legacy_op_util.cc: In function ‘void mxnet::op::RegisterLegacyOpProp()’:
src/nnvm/legacy_op_util.cc:315:8: error: ‘class nnvm::Op’ has no member named ‘attr’
     op.attr<nnvm::FListInputNames>("FListInputNames", OpPropListInputNames);
        ^
src/nnvm/legacy_op_util.cc:315:34: error: expected primary-expression before ‘>’ token
     op.attr<nnvm::FListInputNames>("FListInputNames", OpPropListInputNames);
                                  ^
src/nnvm/legacy_op_util.cc:315:55: warning: left operand of comma operator has no effect [-Wunused-value]
     op.attr<nnvm::FListInputNames>("FListInputNames", OpPropListInputNames);
                                                       ^
src/nnvm/legacy_op_util.cc:316:8: error: ‘class nnvm::Op’ has no member named ‘attr’
     op.attr<nnvm::FListOutputNames>("FListOutputNames", OpPropListOutputNames);
        ^
src/nnvm/legacy_op_util.cc:316:35: error: expected primary-expression before ‘>’ token
     op.attr<nnvm::FListOutputNames>("FListOutputNames", OpPropListOutputNames);
......
```

**Comment by piiswrong** [comment]
what does git status show?

**Comment by starimpact** [comment]
nothing:
```
HEAD detached at b2d222c
You are currently bisecting, started from branch 'master'.
  (use "git bisect reset" to get back to the original branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   make/config.mk

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by starimpact** [comment]
@piiswrong ?
What should I do next?

**Comment by piiswrong** [comment]
try if reverting this commit helps: https://github.com/dmlc/mxnet/commit/9203e3857d05ae982907c75c894668047c51d4a8

**Comment by starimpact** [comment]
ok, I will try it.

**Comment by starimpact** [comment]
```9203e38``` is still slow...

**Comment by starimpact** [comment]
```e027f1c``` can not be compiled.

**Comment by starimpact** [comment]
@piiswrong please give me some advice, I want to solve the problem.

**Comment by piiswrong** [comment]
I think it has something to do with your io pipeline. The problem seems to be coupled with your entire setup. You need to post a reproducible example for others to debug it

**Comment by starimpact** [comment]
but I want to solve it by myself. It is hard to give the reproducible example for this problem.
what should I do if I want to do it?

**Comment by piiswrong** [comment]
try profiler with either nvidia profiler or mxnet profiler

**Comment by starimpact** [comment]
thanks.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
