### ISSUE TITLE
CPP test case fails to compile using gcc 4.8.5 when MKLDNN enabled

### ISSUE THREAD

**Issue by juliusshufan** [apache/incubator-mxnet#10168]
## Description
When compiling the CPP test cases using GCC 4.8.5 with MKLDNN enabled, a compiling error will be raised as below:
_**tests/cpp/operator/mkldnn.cc:37:10: error: ‘align’ is not a member of ‘std’
   ret2 = std::align(alignment, size, mem, space2);**_

This is because std::align requires GCC 5.0 or above, since the minimum requirement for MXNET is gcc 4.8, it is supposed std::align should be replaced.

## Environment info (Required)
CentOS 7.2 64bit

Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)
make -j($nproc) USE_MKLDNN=1 USE_BLAS=mkl test

Compiler (gcc/clang/mingw/visual studio):
GCC 4.8.5

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
Compiling error:
_**tests/cpp/operator/mkldnn.cc:37:10: error: ‘align’ is not a member of ‘std’
   ret2 = std::align(alignment, size, mem, space2);**_

## Steps to reproduce
(Paste the commands you ran that produced the error.)
make -j($nproc) USE_MKLDNN=1 USE_BLAS=mkl USE_OPENCV=1 test

**Comment by marcoabreu** [comment]
@pengzhao-intel

**Comment by juliusshufan** [comment]
@zheng-da

**Comment by pengzhao-intel** [comment]
https://github.com/apache/incubator-mxnet/blob/926f2e231334c5a2832b3b79b31cb4e47dde2b1c/src/operator/nn/mkldnn/mkldnn_base.cc#L28

There is a standalone implementation for `std::align` and we can do a replacement for CPP test.
@juliusshufan do you have interested in submitting a PR?

**Comment by zheng-da** [comment]
This is a unit test to check the correctness of the custom alignment function.

**Comment by TaoLv** [comment]
@zheng-da @marcoabreu Do you mind to skip this test when GCC < 5.0? I cannot find a good approach to replace `std::align` here. Actually, `mxnet::AlignMem` in this test was designed to replace `std::align` and this test was set for comparing the functionality of `mxnet::AlignMem` and `std::align`. If we provide a new align function here, maybe it should be tested too.

**Comment by marcoabreu** [comment]
I don't think this is possible. It's my mistake that I used the wrong GCC version on our CentOS builds and this went through, but in the end we're supposed to support that compiler and apparently there are customers using that version.

**Comment by juliusshufan** [comment]
@marcoabreu Thanks for the information, I think per the description here, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57350, from GCC5.0, the std::align is supported, if my understanding is correct, the minimum requirement of of MXNET is gcc 4.8.

Specifically for this issue, the posix_memalign provided by stdlib might help to replace std::align, but this function is platform-dependent. 
What do you think.

**Comment by marcoabreu** [comment]
Puh that's a bit too much for me, I hope somebody else with a bit more experience in that field could help out here.

**Comment by lebeg** [comment]
Where are the minimum requirements for compiler versions for MXNet builds listed?

**Comment by marcoabreu** [comment]
They are listed at http://mxnet.incubator.apache.org/install/index.html if you press "Build from Source"

**Comment by lebeg** [comment]
I think the version should be one that we are running on the ci. Maybe we can update the documentation on the website? Because it's effectively already 5.0 and clang is not even mentioned (we have ci builds with it AFAIK). Or maybe a question in the dev list?

**Comment by marcoabreu** [comment]
I think we should rather run CI in accordance with our specifications - it was my mistake I used a wrong version. The problem is that customers using CentOS usually rely on older versions of applications and compilers, so I don't think we can drop support for GCC < 5.
@juliusshufan do I understand it right that GCC 4.8.5 is hard constraint for you?

**Comment by juliusshufan** [comment]
@marcoabreu Thanks again for the follow-up.
For me, as I am running CentOS, and the default gcc with it is 4.8.5, it is a better OOB experience that MXNET can keep on supporting this version of the gcc, and I also agree with you that the necessity of supporting to GCC<5.

Thanks.

**Comment by marcoabreu** [comment]
Okay, thank you for your confirmation. I have created a PR to ensure we're validating 4.8.* on CentOS. https://github.com/apache/incubator-mxnet/pull/10200

**Comment by marcoabreu** [comment]
@juliusshufan apparently, our CI is able to compile MXNet using GCC 4.8.5 without any erros: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10200/1/pipeline/48 Could you please try to find the difference between your and our approach?

**Comment by marcoabreu** [comment]
@TaoLv I see. So ```std::align``` is only used as a verification method in our tests and nowhere in our actual codebase?

**Comment by TaoLv** [comment]
Yes. The compiling failure only occures in mkldnn cpp test case.

**Comment by marcoabreu** [comment]
I see. Would you mind adding MKLDNN support to our CentOS 7 cpu environment?

**Comment by TaoLv** [comment]
@marcoabreu Hah, your PR #10200 has passed CI successfully! So I wonder what I can do now.

**Comment by marcoabreu** [comment]
Our CentOS 7 environment is using OpenBLAS and not MKL. The best would probably be to change the configuration to MKLDNN and then fix all upcoming errors.

**Comment by TaoLv** [comment]
Sorry, I don't know much about changing CI environment. I will ping @pengzhao-intel and @xinyu-intel for help. They worked on mkldnn and clang environment before.

**Comment by zheng-da** [comment]
I agree with @TaoLv that we should disable this test for any compiler that doesn't support std::align. This is just a test. Any CI that uses higher-version compilers can test it.

**Comment by marcoabreu** [comment]
I also agree, in this case we can make an exception since we're validating the results in other environments with a more recent compiler version.

**Comment by TaoLv** [comment]
@juliusshufan Please try the latest master branch to see if this issue is still there. Thanks @marcoabreu for merging #10218

**Comment by juliusshufan** [comment]
I think this issue is cleared now. Thanks for all your effort. 👍
