### ISSUE TITLE
Build on Linux will fail if "test" option used

### ISSUE THREAD

**Issue by juliusshufan** [apache/incubator-mxnet#14755]
## Description
There is a build issue happened on MXNet github repo on Linux if using below command:
 make -j USE_OPENCV=1 USE_MKLDNN=1 USE_BLAS=mkl **_### test_**

The build is okay if "test" removed.

@TaoLv @pengzhao-intel 

## Environment info (Required)
GCC 4.8.5
CentOS 7.5

```
What to do:
run  make -j USE_OPENCV=1 USE_MKLDNN=1 USE_BLAS=mkl **_### test_**, build MXNet from source.

```
Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)
Compiler (gcc/clang/mingw/visual studio):
GCC4.8.5

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## What have you tried to solve it?
@zachgk 
The build issue is most likely introduced after commit https://github.com/apache/incubator-mxnet/commit/391a1be260eb75b437ebced6743647b8e9df7802
The commit https://github.com/apache/incubator-mxnet/commit/dc48cd2a5a6460171bf9b842453866e731e6ff7d seems changing the HEAD of 3rdpary/googletest to eb9225c, if I switch the 3rdpary/googletest to previous HEAD ec44c6c , then make -j USE_OPENCV=1 USE_MKLDNN=1 USE_BLAS=mkl test can succeed.

**Comment by frankfliu** [comment]
@mxnet-label-bot add [build]

**Comment by zachgk** [comment]
@larroy Any ideas?

**Comment by TaoLv** [comment]
@juliusshufan Can you try a higher version of GCC? I think it's due to the new googletest is not compatible with GCC 4.8.5.

**Comment by juliusshufan** [comment]
Sure thing and will take a try. Just wondering, is the GCC 4.8.5 still the minimum requirements for MXNet?

**Comment by TaoLv** [comment]
Yes, I think the requirement for GCC is not changed. If the issue is confirmed, it will be a breaking issue for MXNet and should be fixed.
Hi @marcoabreu, is GCC 4.8.5 still in the CI validation set?

**Comment by larroy** [comment]
What is the error?

For me is MKL problem:

```
make[1]: 'libdmlc.a' is up to date.  
make[1]: Leaving directory '/home/piotr/mxnet_master/3rdparty/dmlc-core'                                                      
sparse_matrix.cc:4:10: fatal error: mkl_spblas.h: No such file or directory                                                   
 #include <mkl_spblas.h>    
```

**Comment by larroy** [comment]
This works for me
```
make -j USE_OPENCV=1 USE_MKLDNN=1 USE_BLAS=open test | tee build.log
```

**Comment by larroy** [comment]
@mxnet-label-bot add [MKL]

**Comment by larroy** [comment]
@mxnet-label-bot add [Build]

**Comment by juliusshufan** [comment]
@larroy Thanks for the follow-up, at my side, the compilation is successful with gcc6.3.1
on using make -j USE_OPENCV=1 USE_MKLDNN=1 USE_BLAS=openblas test

But it will fail on gcc 4.8.5/5.3.1, logs as below. seems it more like a GCC compatibility issue. If the GCC4.8.5 is still the minimum requirement for MXNet, could you please try with gcc 4/5. 

USE_BLAS=open：
#gcc5.3.1)
    60 g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/torch/workspace/sourc     e/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/plan_memory.cc -o build/src/pass/plan_memory.o
  61 In file included from 3rdparty/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
  62                  from 3rdparty/googletest/googletest/include/gtest/gtest.h:60,
  63                  from 3rdparty/googletest/googletest//src/gtest-all.cc:38:
  64 3rdparty/googletest/googletest/include/gtest/internal/gtest-port.h:830:12: error: ‘std::get’ has not been declared
  65  using std::get;
  66             ^
  67 3rdparty/googletest/googletest/include/gtest/internal/gtest-port.h:831:12: error: ‘std::make_tuple’ has not been declared
  68  using std::make_tuple;
  69             ^
  70 3rdparty/googletest/googletest/include/gtest/internal/gtest-port.h:832:12: error: ‘std::tuple’ has not been declared
  71  using std::tuple;
#gcc4.8.5)
  42 /usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is c     urrently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
  43  #error This file requires compiler and library support for the \
  44   ^
  45 ^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0In file included from 3rdparty/googletest/googletest/include/gtest/internal/gtes     t-internal.h:40:0,
  46                  from 3rdparty/googletest/googletest/include/gtest/gtest.h:60,
  47                  from 3rdparty/googletest/googletest//src/gtest-all.cc:38:
  48 3rdparty/googletest/googletest/include/gtest/internal/gtest-port.h:830:12: error: ‘std::get’ has not been declared
  49  using std::get;
  50             ^
  51 3rdparty/googletest/googletest/include/gtest/internal/gtest-port.h:831:12: error: ‘std::make_tuple’ has not been declared
 
USE_BLAS=openblas：
#gcc5.3.1)
  41 /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
  42  #error This file requires compiler and library support \
  43   ^
  44   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  45                                  Dload  Upload   Total   Spent    Left  Speed
  46 ^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/in     clude -I../3rdparty/HalideIR/src -I../topi/include -I/home/torch/workspace/source/incubator-mxnet/3rdparty/dmlc-core/include  -c src/core/node.cc -o build/src/c     ore/node.o
 
#gcc4.8.5)
22 /usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is c     urrently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
  23  #error This file requires compiler and library support for the \
  24   ^
  25 g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o recordio.o src/recordi     o.cc

**Comment by larroy** [comment]
Can you print full compiler invocation? looks like std=c++11 is missing, so it can't find make_tuple. I think this is an easy Makefile fix.

**Comment by TaoLv** [comment]
@larroy this line? https://github.com/apache/incubator-mxnet/blob/master/tests/cpp/unittest.mk#L39

**Comment by larroy** [comment]
@TaoLv can you add -std=c++11  as in the lines below?

**Comment by larroy** [comment]
better to replace c++0x to c++11

**Comment by bgawrych** [comment]
@mxnet-label-bot remove [MKL]

**Comment by bgawrych** [comment]
@szha seems to be issue with googletest and old GCC version - I'm not sure if it should be investigated more - with newer GCC version there is no issue - what do you think?

**Comment by leezu** [comment]
GCC4.8.5 is no longer supported on the master branch. So I think we can close this issue.
